# Generated by Django 2.0.2 on 2018-02-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street_address', models.CharField(max_length=500)),
                ('gplaces_json', models.FileField(upload_to='')),
                ('gmaps_json', models.FileField(upload_to='')),
            ],
        ),
    ]
